#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class Image;
                ref class TextBox;
            }
        }
    }
}

namespace App5
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Button^ button;
        private: ::Windows::UI::Xaml::Controls::Button^ button2;
        private: ::Windows::UI::Xaml::Controls::Button^ button3;
        private: ::Windows::UI::Xaml::Controls::Button^ button4;
        private: ::Windows::UI::Xaml::Controls::Button^ button5;
        private: ::Windows::UI::Xaml::Controls::Image^ imageBox;
        private: ::Windows::UI::Xaml::Controls::Button^ startbtn;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBox1;
    };
}

